[package]
name = "sfcgal"
version = "0.1.0"
authors = ["Matthieu Viry <matthieu.viry@univ-grenoble-alpes.fr>"]
license = "MIT/Apache-2.0"
edition = "2018"
description = """
High-level bindings to SFCGAL and conversion from/to other geometry libraries.
"""
readme = "README.md"
homepage = "https://github.com/mthh/sfcgal-rs"
repository = "https://github.com/mthh/sfcgal-rs"
keywords = ["geometry", "geospatial", "gis", "sfcgal"]
categories = ["algorithms", "api-bindings"]


[dependencies]
sfcgal-sys = "0.1.0"
failure = "^0.1"
libc = "0.2.48"
geo-types = "0.4"
enum-primitive-derive = "^0.1"
num-traits = "^0.1"
approx = "0.3"
geojson = "0.15"
