[package]
name = "sfcgal-rs"
version = "0.1.0"
authors = ["Matthieu Viry <matthieu.viry@univ-grenoble-alpes.fr>"]
edition = "2018"

[dependencies]
sfcgal-sys = { git = "https://github.com/mthh/sfcgal-sys" }
failure = "*"
libc = "*"
geo-types = "0.3"
enum-primitive-derive = "^0.1"
num-traits = "^0.1"
approx = "0.3"
